name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with: { go-version: 1.25 }

      - name: Test
        run: go test -v -coverpkg ./... ./... | tee test.out

      - name: Publish test and coverage metrics
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: fbde4d59b7dd3c4f2cc9c4fea3497ae1
          token: ${{ secrets.GIST_TOKEN }}

      - name: Build (Linux)
        run: go build -ldflags="-s -w" -o "propencrypt" "cmd/propencrypt.go"
        env: { GOARCH: amd64, GOOS: linux }

      - name: Build (Windows)
        run: go build -ldflags="-s -w" -o "propencrypt.exe" "cmd/propencrypt.go"
        env: { GOARCH: amd64, GOOS: windows }

      - name: Package (Linux)
        run: |
          archive=propencrypt_linux_amd64.tar.gz
          tar zcvf "${archive}" propencrypt
          sha256sum "${archive}" | cut -d' ' -f 1 > "${archive}.sha256"

      - name: Package (Windows)
        shell: pwsh
        run: |
          $archive = 'propencrypt_windows_amd64.zip'
          Compress-Archive 'propencrypt.exe' -DestinationPath "$archive" -CompressionLevel 'Optimal'
          $hash = (Get-FileHash -Algorithm 'SHA256' "$archive").Hash.ToLower()
          Set-Content -Path "$archive.sha256" -Value "$hash`n" -Encoding 'ascii' -NoNewline

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: propencrypt
          path: propencrypt*

  npm-package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with: { node-version: 24 }

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with: { name: propencrypt }

      - name: Package
        run: bash ./build/package/npm/scripts/package.sh

      - name: Test
        run: bash ./build/package/npm/scripts/test.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: propencrypt-npm-package
          path: build/package/npm/*.tgz
